###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:postgresql://ec2-18-191-110-90.us-east-2.compute.amazonaws.com:5432/postgres?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: postgres
    password: integrate
    driverClassName: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: create
        default_schema: SCHEMA_NAME
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: false